name: trolleyspeedx3
version: '1.0-SNAPSHOT'
main: org.kxysl1k.trolleyspeedx3.Trolleyspeedx3
api-version: '1.21'
authors: [ Kxysl1k ]
description: Plugin By Kxysl1k
website: https://kxysl1k.netlify.app/
